apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-argo-app
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 61.3.2
      helm:
        valueFiles:
          - $values/apps/prometheus/values.yaml
          - $values/apps/prometheus/values-prod.yaml  # env specific args

    - repoURL: https://github.com/MPriv32/minikube-k8s-platform-demo.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # Pulls at 3min intervals
    automated:
      selfHeal: true
      prune: true
